/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RecordingsIndexRouteImport } from './routes/recordings/index'
import { Route as ChangelogIndexRouteImport } from './routes/changelog/index'
import { Route as BrowseIndexRouteImport } from './routes/browse/index'
import { Route as AnimeIdIndexRouteImport } from './routes/anime/$id/index'
import { Route as ErrorsStatusCodeIndexRouteImport } from './routes/_errors/$statusCode/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecordingsIndexRoute = RecordingsIndexRouteImport.update({
  id: '/recordings/',
  path: '/recordings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogIndexRoute = ChangelogIndexRouteImport.update({
  id: '/changelog/',
  path: '/changelog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrowseIndexRoute = BrowseIndexRouteImport.update({
  id: '/browse/',
  path: '/browse/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIdIndexRoute = AnimeIdIndexRouteImport.update({
  id: '/anime/$id/',
  path: '/anime/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorsStatusCodeIndexRoute = ErrorsStatusCodeIndexRouteImport.update({
  id: '/_errors/$statusCode/',
  path: '/$statusCode/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/browse/': typeof BrowseIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/recordings/': typeof RecordingsIndexRoute
  '/$statusCode/': typeof ErrorsStatusCodeIndexRoute
  '/anime/$id/': typeof AnimeIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/browse': typeof BrowseIndexRoute
  '/changelog': typeof ChangelogIndexRoute
  '/recordings': typeof RecordingsIndexRoute
  '/$statusCode': typeof ErrorsStatusCodeIndexRoute
  '/anime/$id': typeof AnimeIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/browse/': typeof BrowseIndexRoute
  '/changelog/': typeof ChangelogIndexRoute
  '/recordings/': typeof RecordingsIndexRoute
  '/_errors/$statusCode/': typeof ErrorsStatusCodeIndexRoute
  '/anime/$id/': typeof AnimeIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/browse/'
    | '/changelog/'
    | '/recordings/'
    | '/$statusCode/'
    | '/anime/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/browse'
    | '/changelog'
    | '/recordings'
    | '/$statusCode'
    | '/anime/$id'
  id:
    | '__root__'
    | '/'
    | '/browse/'
    | '/changelog/'
    | '/recordings/'
    | '/_errors/$statusCode/'
    | '/anime/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrowseIndexRoute: typeof BrowseIndexRoute
  ChangelogIndexRoute: typeof ChangelogIndexRoute
  RecordingsIndexRoute: typeof RecordingsIndexRoute
  ErrorsStatusCodeIndexRoute: typeof ErrorsStatusCodeIndexRoute
  AnimeIdIndexRoute: typeof AnimeIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recordings/': {
      id: '/recordings/'
      path: '/recordings'
      fullPath: '/recordings/'
      preLoaderRoute: typeof RecordingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog/': {
      id: '/changelog/'
      path: '/changelog'
      fullPath: '/changelog/'
      preLoaderRoute: typeof ChangelogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/browse/': {
      id: '/browse/'
      path: '/browse'
      fullPath: '/browse/'
      preLoaderRoute: typeof BrowseIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/$id/': {
      id: '/anime/$id/'
      path: '/anime/$id'
      fullPath: '/anime/$id/'
      preLoaderRoute: typeof AnimeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_errors/$statusCode/': {
      id: '/_errors/$statusCode/'
      path: '/$statusCode'
      fullPath: '/$statusCode/'
      preLoaderRoute: typeof ErrorsStatusCodeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrowseIndexRoute: BrowseIndexRoute,
  ChangelogIndexRoute: ChangelogIndexRoute,
  RecordingsIndexRoute: RecordingsIndexRoute,
  ErrorsStatusCodeIndexRoute: ErrorsStatusCodeIndexRoute,
  AnimeIdIndexRoute: AnimeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
