import { v5 as uuidv5 } from 'uuid'

const NAMESPACE = uuidv5('animetracker', uuidv5.DNS)

interface Episode {
  episodeNumber: number
  episodeId: string
  title: string
  description: string
  releaseDate: string
  duration: number
  maturityRating: number | null
  imageUrl: string
  hasSubtitles: boolean
  hasDub: boolean
  benefitId: string | null
}

interface Season {
  seasonId: string
  displayName: string
  seasonNumber: number
  imageUrl: string | null
  year: number | null
  quarter: number | null
  episodes: Episode[]
}

interface Title {
  contentId: string
  title: string
  description: string
  entityType: string
  maturityRating: number | null
  imageUrl: string | null
  benefitId: string | null
  tmdbId?: number | null
  anilistId?: number | null
  status?: string
  year?: number | null
  quarter?: number | null
  seasons: Season[]
}

function esc(value: string): string {
  return value.replace(/'/g, "''")
}

function sqlVal(value: unknown): string {
  if (value === null || value === undefined) return 'NULL'
  if (typeof value === 'boolean') return value ? '1' : '0'
  if (typeof value === 'number') return String(value)
  return `'${esc(String(value))}'`
}

async function loadTitles(provider: string): Promise<{ provider: string; titles: Title[] }> {
  const path = `__tests__/fixtures/${provider}/episodes_identified.json`
  const titles: Title[] = await Bun.file(path).json()
  console.log(`Loaded ${titles.length} titles from ${path}`)
  return { provider, titles }
}

function generateSql(allData: { provider: string; titles: Title[] }[]): string[] {
  const lines: string[] = []
  const now = new Date().toISOString()

  lines.push('-- Generated by scripts/seed.ts')
  lines.push(`-- ${now}`)
  lines.push('')
  lines.push('DELETE FROM episodes;')
  lines.push('DELETE FROM seasons;')
  lines.push('DELETE FROM anime;')
  lines.push('')

  let animeCount = 0
  let seasonCount = 0
  let episodeCount = 0

  for (const { provider, titles } of allData) {
    // contentIdの重複を除去
    const seenContentIds = new Set<string>()
    const dedupedTitles = titles.filter((t) => {
      if (seenContentIds.has(t.contentId)) return false
      seenContentIds.add(t.contentId)
      return true
    })

    lines.push(`-- ${provider}: ${dedupedTitles.length} titles`)
    lines.push('')

    for (const title of dedupedTitles) {
      const animeId = uuidv5(`${provider}:${title.contentId}`, NAMESPACE)

      const year = title.year ?? 0
      const quarter = title.quarter ?? 0
      const status = title.status ?? 'UNKNOWN'

      lines.push(
        `INSERT INTO anime (id, title, description, provider, content_id, entity_type, maturity_rating, image_url, benefit_id, year, quarter, is_identified, status, tmdb_id, anilist_id, created_at, updated_at) VALUES (${sqlVal(animeId)}, ${sqlVal(title.title)}, ${sqlVal(title.description)}, ${sqlVal(provider)}, ${sqlVal(title.contentId)}, ${sqlVal(title.entityType)}, ${sqlVal(title.maturityRating)}, ${sqlVal(title.imageUrl)}, ${sqlVal(title.benefitId)}, ${sqlVal(year)}, ${sqlVal(quarter)}, 1, ${sqlVal(status)}, ${sqlVal(title.tmdbId)}, ${sqlVal(title.anilistId)}, ${sqlVal(now)}, ${sqlVal(now)});`,
      )
      animeCount++

      for (const season of title.seasons) {
        const seasonUuid = uuidv5(`${provider}:${title.contentId}:${season.seasonId}`, NAMESPACE)

        lines.push(
          `INSERT INTO seasons (id, anime_id, season_id, display_name, season_number, image_url, created_at) VALUES (${sqlVal(seasonUuid)}, ${sqlVal(animeId)}, ${sqlVal(season.seasonId)}, ${sqlVal(season.displayName)}, ${sqlVal(season.seasonNumber)}, ${sqlVal(season.imageUrl)}, ${sqlVal(now)});`,
        )
        seasonCount++

        const seenEpNumbers = new Set<number>()
        for (const ep of season.episodes) {
          if (seenEpNumbers.has(ep.episodeNumber)) continue
          seenEpNumbers.add(ep.episodeNumber)
          const epUuid = uuidv5(`${provider}:${title.contentId}:${season.seasonId}:${ep.episodeNumber}`, NAMESPACE)

          lines.push(
            `INSERT INTO episodes (id, season_id, episode_number, episode_id, title, description, release_date, duration, maturity_rating, image_url, has_subtitles, has_dub, benefit_id, recorded, created_at) VALUES (${sqlVal(epUuid)}, ${sqlVal(seasonUuid)}, ${sqlVal(ep.episodeNumber)}, ${sqlVal(ep.episodeId)}, ${sqlVal(ep.title)}, ${sqlVal(ep.description)}, ${sqlVal(ep.releaseDate)}, ${sqlVal(ep.duration)}, ${sqlVal(ep.maturityRating)}, ${sqlVal(ep.imageUrl)}, ${sqlVal(ep.hasSubtitles)}, ${sqlVal(ep.hasDub)}, ${sqlVal(ep.benefitId)}, 0, ${sqlVal(now)});`,
          )
          episodeCount++
        }
      }

      lines.push('')
    }
  }

  console.log(`\nGenerated: ${animeCount} anime, ${seasonCount} seasons, ${episodeCount} episodes`)
  return lines
}

const LINES_PER_FILE = 10000

const allData = await Promise.all([loadTitles('amazon'), loadTitles('hulu')])

const lines = generateSql(allData)
const outputDir = 'scripts/seed'

const { mkdirSync, rmSync } = await import('node:fs')
rmSync(outputDir, { recursive: true, force: true })
mkdirSync(outputDir, { recursive: true })

const fileCount = Math.ceil(lines.length / LINES_PER_FILE)
for (let i = 0; i < fileCount; i++) {
  const chunk = lines.slice(i * LINES_PER_FILE, (i + 1) * LINES_PER_FILE)
  const filename = `${outputDir}/${String(i).padStart(4, '0')}.sql`
  await Bun.write(filename, chunk.join('\n'))
}
console.log(`Output: ${outputDir}/ (${fileCount} files)`)
